#@ load("@ytt:data", "data")

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kapp.k14s.io/change-group: external-dns
    kapp.k14s.io/change-rule.serviceaccount-del: "delete before deleting external-dns-serviceaccount"
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: external-dns-overlay
  name: external-dns
  namespace: external-dns-install
spec:
  packageRef:
    refName: external-dns.tanzu.vmware.com
    versionSelection:
      constraints: ">=0.11.0 <1.0.0"
  serviceAccountName: external-dns-install-sa
  values:
  - secretRef:
      key: inline-values
      name: external-dns-values
---
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-values
  namespace: external-dns-install
stringData:
  #@yaml/text-templated-strings
  inline-values: |
    deployment:
        args:
        - --source=service
        - --provider=azure
        - --policy=upsert-only
        - --registry=txt
        - --txt-prefix=externaldns-
        - --domain-filter=(@= data.values.domain @)
        - --azure-resource-group=(@= data.values.azure.resource_group @)
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: route53-credentials
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: route53-credentials
              key: aws_secret_access_key

---
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-overlay
  namespace: external-dns-install
stringData:
  #@yaml/text-templated-strings
  secret.yaml: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: route53-credentials
      namespace: tanzu-system-service-discovery
    stringData:
      tenantId: (@= data.values.azure.tenant_id @)
      subscriptionId: (@= data.values.azure.subscription_id @)
      resourceGroup: (@= data.values.azure.resource_group @)
      useManagedIdentityExtension: "true"